baseURL = 'https://skyboymi.github.io/sunflowers/'
defaultContentLanguage = 'zh'
languageCode = 'zh-Hans'
title = 'My Hugo Blog'
theme = 'dream'
enableRobotsTXT = true
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[params]
  lightTheme = 'emerald'
  darkTheme = 'forest'
  author = 'Skyboymi'
  avatar = 'img/avatar.svg'
  headerTitle = 'My Hugo Blog'
  siteStartYear = 2026
  rss = true

[params.navItems]
  cryptoRss = { href = '/crypto-rss/', icon = 'logo-rss', title = 'Crypto RSS' }

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
